deploy:
  docker:
    - image: circleci/node:10.16.3
  steps:
    - add_ssh_keys:
        fingerprints:
          - "SHA256:G5/q3yjPob4UfwCKkX0RMS+2f7WUjkyNS4FTDe0dwvk"
    - checkout
    - run:
        name: Clone repo on EC2
        command: |
          ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "
            rm -rf ExampleApplication &&
            git clone https://github.com/EKL-NCI/devopsecLab2 ExampleApplication
          "
    - run:
        name: Upload deploy.sh
        command: |
          scp deploy.sh $EC2_USERNAME@$EC2_PUBLIC_DNS:~/ExampleApplication/deploy.sh
    - run:
        name: Execute deploy.sh
        command: |
          ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "bash ~/ExampleApplication/deploy.sh"